### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by aaronto0705** [CMU-313/fall22-hw3-amy-and-her-friends#11]
Write tests to check that Reviews are added properly to the db and that tests are automated.

**Comment by aaronto0705** [comment]
Write tests to check that Reviews are added properly to the db and that tests are automated.

**Comment by fuhaowei** [comment]
Testing we wrote was completed based on the acceptance criteria we had determined previously. 

1) Logging in as a basic user , and making sure that the session was valid. 

2) Creating a new form with the correct 3 parameters

3) Returning a valid RevID post the successful creation of the form.
